# General settings
name: 'general'   
project: 'retrodiffuser'
task: 'rxn' 
resume_from_last_n: 1
gpus: 1                     # Multi-gpu is not implemented on this branch
log_every_steps: 50
wandb:
  entity: your_entity
  project: your_project
  mode: online
  resume: false
  run_id: null
  run_name: null
  group: default
  tags: ["default"]
  checkpoint_epochs: null
  eval_sampling_steps: null
  nfiles: null # used to identify sample files when using array jobs
  sample_file_name: null
  load_run_config: null
