name: 'uspto-mit'
dataset_nb: ''
datadir: 'data/uspto-mit'
datadist_dir: 'data/uspto-mit'
pin_memory: False
remove_h: False
shuffle: True
with_explicit_h: False
with_formal_charge: True
add_supernode_edges: True
nb_rct_dummy_nodes: 35
num_workers: 4
batchsize_bins: {'train': [128, 64, 16], 'test': [64], 'val': [64]}
size_bins: {'train': [64, 83, 102], 'test': [250],'val': [250]}
canonicalize_molecule: True # Should always be true, used in case the data has atom mapping & we want to canonicalize the molecule to remove information leak from atom mapping order
atom_types: ['Rh', 'Pd', 'I-1', 'Rh+2', 'B+3', 'Mg+2', 'Sn+3', 'Pd+2', 'Br-1', 'Zn', 'Nd', 'Pd-4', 'Ta+5', 'Ti+4', 
             'Ag+1', 'Al-1', 'B', 'Co+2', 'C-1', 'Yb+3', 'Sc+3', 'Ru', 'Fe+2', 'Cr', 'Pb', 'In', 'Zr', 'Cl', 'Al+1', 
             'S', 'Ni+2', 'In+3', 'Co', 'Li+1', 'N', 'Ba+2', 'Ca', 'Pb+2', 'S+1', 'O+1', 'K+1', 'Ca+2', 'Bi', 'Li', 'Mn+2', 
             'Rh+3', 'Br', 'Sc', 'Hg', 'Cu', 'Tl+3', 'I+1', 'Cs+1', 'Mg', 'Ag', 'Mo', 'Ti+3', 'Sn+1', 'P-1', 'I', 'Si-1', 
             'Al+3', 'Cl+2', 'Cu+2', 'Ge', 'Zr+4', 'Ti', 'S-1', 'Sm+3', 'Au', 'Ru+2', 'P', 'Nd+1', 'I+3', 'Re', 'Zn+1', 'Ta', 
             'Pt', 'Ni', 'Ce+4', 'Al', 'Ag+2', 'Pb+4', 'Ce', 'K', 'Os', 'N+1', 'Sn+2', 'O-1', 'N-1', 'Fe-3', 'H-1', 'Se', 'O', 
             'Mg+1', 'Mn', 'Na+1', 'Rh+1', 'C', 'Ar', 'Ce+3', 'As', 'Cu+1', 'Si+1', 'F', 'Zn+2', 'B+1', 'C+4', 'Ag-1', 'Si', 
             'Cl+1', 'Fe', 'Hg+1', 'Cl+3', 'P+5', 'Sb', 'Na', 'I+2', 'Hg+2', 'Al+2', 'C+1', 'B-1', 'W', 'F-1', 'Br+2', 'Cl-1', 
             'B+2', 'Sn', 'H', 'H+1', 'P+1', 'Fe+3', 'U', 'SuNo']
allowed_bonds:
  'O': [2]
  'C': [4]
  'N': [3]
  'I': [1, 3, 5, 7]
  'Cl': [1]
  'Si': [4, 6]
  'F': [1]
  'Br': [1]
  'N+1': [4]
  'O-1': [1]
  'S': [2, 4, 6]
  'B': [3]
  'N-1': [2]
  'Zn+1': [3]
  'Cu': [1, 2] 
  'Sn': [2, 4]
  'P+1': [4, 6, 8]
  'Mg+1': [3]
  'C-1': [3]
  'P': [3, 5, 7]
  'S+1': [3, 5, 7]
  'S-1': [1, 3, 5]
  'Se': [2, 4, 6]
  'Zn': [2]
  'Mg': [2]
  'U': [6]
  'Au': [0]
dataset_size:
  train: 409035
  test: 40000
  val: 30000